import type { Metadata } from "next";
import "./globals.css";
import { Barlow } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow = Barlow({
  subsets: ["latin"], // Choose the subsets you need
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Choose font weights you need
  variable: "--font-barlow", // Optional, if you use CSS variables
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
